### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Roby1164** [GKaszewski/disintegrator-mod#1]
Trying on my server, it crashes as soon as I click on the disintegrator. You can build it, place it, but not use it, it closes the server.
I am attaching my crash file.
[crash-2023-07-01_23.38.33-server.txt](https://github.com/GKaszewski/disintegrator-mod/files/11927203/crash-2023-07-01_23.38.33-server.txt)

**Comment by GKaszewski** [comment]
Thanks for the report, I will try to fix it asap

**Comment by Roby1164** [comment]
It crashes with both version 1.0.0 and version 1.0.2.
I did the test, to check that it wasn't a problem with the recent version.
This is the 1.0.2 crash log
[crash-2023-07-01_23.31.32-server.txt](https://github.com/GKaszewski/disintegrator-mod/files/11927208/crash-2023-07-01_23.31.32-server.txt)

**Comment by GKaszewski** [comment]
Okay, I fixed it ;)
Mod version: 1.0.3 has this issue resolved.
